govsso-inproxy:
  admin:
    base-url: https://admin.localhost:443
    tls:
      trust-store: classpath:inproxy.localhost.admin.truststore.p12
      trust-store-password: changeit
  hydra:
    base-url: ${GOVSSO_HYDRA_URL:https://hydra.localhost:8443}
  session:
    base-url: ${GOVSSO_SESSION_URL:https://session.localhost:15443}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true

server:
  port: 13443
  forward-headers-strategy: NATIVE # Under main this cannot be enabled by default, because docker-compose.yml doesn't have another proxy in front of inproxy that would always set X-Forwarded-For header. X-Forwarded-For value that could be set outside of your own infrastructure, cannot be trusted.
  ssl:
    enabled: true
    enabled-protocols: TLSv1.3
    key-store: classpath:inproxy.localhost.keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    protocol: TLS

spring:
  application:
    name: govsso-inproxy
  main:
    banner-mode: off
  cloud:
    gateway:
      httpclient:
        ssl:
          trustedX509Certificates:
            - classpath:govsso-ca.localhost.crt
      default-filters:
        - RemoveRequestHeader=traceparent
        - RemoveRequestHeader=tracestate
        - RemoveRequestHeader=elastic-apm-traceparent
      routes:
        - id: hydra-well-known
          uri: ${govsso-inproxy.hydra.base-url}
          predicates:
            - Path=/.well-known/openid-configuration,/.well-known/jwks.json
        - id: oauth2-auth
          uri: ${govsso-inproxy.hydra.base-url}
          predicates:
            - Path=/oauth2/auth
          filters:
            - TraceParentFilter
            - PromptFilter
        - id: oauth2-sessions-logout
          uri: ${govsso-inproxy.hydra.base-url}
          predicates:
            - Path=/oauth2/sessions/logout
          filters:
            - TraceParentFilter
        - id: oauth2-token
          uri: ${govsso-inproxy.hydra.base-url}
          predicates:
            - Path=/oauth2/token
          filters:
            - IpFilter
        - id: admin
          uri: ${govsso-inproxy.session.base-url}
          predicates:
            - Path=/admin**,/admin/**
          filters:
            - RewritePath=/admin.*, /notfound
        - id: root
          uri: https://example.com # Not used, but valid URI is required by Spring
          filters:
            - RedirectTo=302, https://www.ria.ee/riigi-infosusteem/elektrooniline-identiteet-ja-usaldusteenused/kesksed-autentimisteenused#govsso
          predicates:
            - Path=/
        - id: default
          order: 9999 # Very low priority compared to the other routes (order value is 0 by default)
          uri: ${govsso-inproxy.session.base-url}
          predicates:
            - Path=/**
